### ISSUE TITLE
subband-ids error

### ISSUE THREAD

**Issue by nicholebarry** [cjordan/mongoose#1]
I've tried inputting specific subband-ids to no avail. Fortunately, I want to run on the full set, which is default. I've tried various subsets of the list below, all have the same error.

Example call:
```
rts-in-file-generator patch --rfi-flagging --base-dir /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000 --metafits /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000/1061312152.metafits --srclist srclist_pumav3_EoR0aegean_EoR1pietro+ForA_1061312152_patch1000.txt --subband-ids 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 --num-cals 1
```
Error:
```error: Invalid value for '--subband-ids <subband-ids>...': invalid digit found in string```

**Comment by cjordan** [comment]
This is an unfortunate consequence of trying to parse multiple inputs associated with a single flag.  The error would be much more helpful if it indicated that it's trying to parse `24 --num-cals 1` as a number.  Anyway, to get around this, this command should work as intended:

`rts-in-file-generator patch --rfi-flagging --base-dir /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000 --metafits /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000/1061312152.metafits --srclist srclist_pumav3_EoR0aegean_EoR1pietro+ForA_1061312152_patch1000.txt --num-cals 1 --subband-ids 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24`

EDIT: Apologies, spoke too soon, this doesn't  work either. Investigating.

**Comment by cjordan** [comment]
OK, annoyingly, the commas aren't expected; they should be spaces instead.  Please try this:

`rts-in-file-generator patch --rfi-flagging --base-dir /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000 --metafits /astro/mwaeor/MWA/data/1061312152/2020-09-12_0000/1061312152.metafits --srclist srclist_pumav3_EoR0aegean_EoR1pietro+ForA_1061312152_patch1000.txt --num-cals 1 --subband-ids 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24`

I could make both versions work with another commit.  Let me know what you think.
