### ISSUE TITLE
num-cals and num-primary-cals

### ISSUE THREAD

**Issue by nicholebarry** [cjordan/mongoose#2]
The option for the number of calibrators seems to have an inherently different meaning from an outside perspective between the patch and peel modes.

I want these options in my .in file:
**patch**
`NumberOfCalibrators=1`
**peel**
`NumberOfCalibrators=5`
`NumberOfIonoCalibrators=1000` 

To set this for **peel**, these options need to be passed:
`--num-primary-cals 5`
`--num-cals 1000`

To set this for **patch**, this option needs to be passed:
`--num-cals 1`

However, it would seem as though the logical option for **patch** should be `--num-primary-cals 1`. This errors because the required param `num-cals` isn't given. I know that `num-cals` defaults `num-primary-cals`, but from an outside perspective, it almost appears as though I'm trying to set `NumberOfIonoCalibrators` in **patch**.

**Comment by cjordan** [comment]
Yep, this was a mistake on my part.  `--num-cals` should only be needed in the peel mode.  I actually had fixed this already this week, but was afraid of pushing in case it broke anything you'd already done :)

**Comment by cjordan** [comment]
I've made a new module `mongoose/master` on garrawarla.  Please let me know if that works for you and we can close this issue.

**Comment by nicholebarry** [comment]
Yes, that seems to have worked.
